module.exports.GET_ALL_PRODUCTS = '/api/products/';
module.exports.ELSLY_PORT = 4000;
module.exports.DOT_ENV_PATH = "../.env";
module.exports.SL_LOGIN_URL = "https://login.salesforce.com";
module.exports.SF_TOKEN = "JAhorxWy5ajdSULgUZJUTpvxd";
module.exports.SF_USERNAME = "tiemenihapi@hapidev.com";
module.exports.SF_PASSWORD = "Masochisme18";
module.exports.PROCESS_PAYMENT = '/payment';
module.exports.PROCESS_REGISTRATION = "/register";
module.exports.PROCESS_SIGNUP = "/sign-in";
module.exports.SECRET_KEY = "a98bc12def7xz5634jmnjk";
module.exports.ONE_DAY = 1 * 24 * 60 * 60 * 1000;
module.exports.JWT_KEY = "jwt";
module.exports.EMPTY_STRING = "";
module.exports.NULL_DURATION = 0